### ISSUE TITLE
Bar updates

### ISSUE THREAD

**Issue by QartemisT** [DeadlyBossMods/DBM-Unified#4]
Tracking list for bar releated features todo;

- [x] Reversed sort by remaining timer [#410]
- [ ] Bar apperances per-bar (large/small) [#409]
- [ ] Support custom bar "groups" and positionings. [#360]
- [x] All the pretty things [Me]

**Comment by MysticalOS** [comment]
For ages, The "style" of bar has been DBM (Classic) and Simple (No animation)

But in reality the drop down toggles two behaviors not one, an these need to be split

Behavior 1
Animation: The bar either animatinos from small bars to large, or instantly teleports there (No Animation).
Behavior 2
Bar Restart: When the bar reaches "enlarge" threshold, it either continues counting down with original sizing, or it restarts from that threshold.

The two features being hacked together is not actually ideal for full customizing. It should be Split into two logical options and the "type/style" drop down probably removed

Option 1: "Animate bar moving between small and large anchor"
Option 2: "Restart bar when it reaches enlarge threshold (if enlarge is disabled, it will restart on the small anchor)"

**Comment by MysticalOS** [comment]
- [ ] Add option to hide bars over <n> active bars.

This would need to be coded a particular way do to fact we don't want to break bar methods like GetRemaining or GetTime as these would fail if bar doesn't exist, we want hidden bars to exist so it's more likely we'll just set the transparency to fully transparent so they are effectively invisible.

The way I propose is added the code to the Bar sorting method which already has information like number of bars, and after sorting them could simply go "and now bars n+ in table should be fully transparent"

As long as sort function is called on any bar being expired or added (and i think it already is) this would work just fine.
