### ISSUE TITLE
New GUI TODO

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Unified#70]
Features:
- [ ] Add checkbox to show description while expanded (off by default)
- [x] Spell icon on spell name
- [ ] Heroic or Mythic icon next to spell name/header itself, if that field is entered on any of special warnings combined into it. Ex merciless on sylvanas in chains of domination. Since spec warn identifies it as a mythic mechanic, auto add icon to header?
- [ ] If user disables group by ability, AddLine needs to be smarter and still add lies to each sub category in use in the mod. (Ie timers, icons, nameplates, announcements if mod.NoSortAnnounce is true)
- [x] Add option to just say "Show classic DBM gui layout only" which basically tells it to ignore "newoption" because you just KNOW someone will ask for it
- [x] Add an option to choose whether icons bundled with abilities, or placed together in icons cat at bottom. with icons cat at bottom being the default. I see the merit of both ways. Some want to see it bundled together for cohesion but another will want them all together to be able to quick glance "what icons this mod uses"
- [x] Add checkbox to auto expand all by default (likely off by default but may survey this one)

Bugs:
- [x] Lua error can be triggered clicking very close (but not on) the + / - button that expands/collapses the spell Desc box
- [x] DBM doesn't work anymore (all timers and warnings just throw lua errors. Even test mod and pull timers fail
- [x] Nameplate auras should be grouped up. currently they aren't. or not consistently (such as 357735 on painsmith)
- [x] Infoframes and range frames using spellId should be grouped up, ones NOT using spellid should not. MysticalOS will go through mods that are using spellids for frames being used by more than one mechanic and fix them to use the "overview" locales so they don't incorrectly get grouped. Basically if it's nil or a string on a range frame or infoframe, don't bundle, number, bundle it like a spellid
- [x] Achievements timers are not properly parsed
- [x] `mod:NewAddsLeftAnnounce` objects are still not combined properly (example, wise marl in mop dungeons) ([see comments for details](https://github.com/DeadlyBossMods/DBM-Unified/issues/70#issuecomment-1043647757))
- [x] Mysterious Lua error? ([see comments for details](https://github.com/DeadlyBossMods/DBM-Unified/issues/70#issuecomment-1042577645))

Changes:

- [x] Spell name header (above spell descriptions) font size should be bigger, prob about the size of option text (or maybe configurable)
- [x] Spell name header should probably  at least be a diff color than spell descriptions.
- [x] Do something when something just literally has no description (such as https://wow.tools/dbc/?dbc=journalencountersection&build=9.2.0.42069#page=1&search=Bleakwing%20Assassin)

**Comment by MysticalOS** [comment]
Lua errors for reference for bug 2

`1x bad argument #1 to '?' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@SharedXML\OptionsFrameTemplates.lua"]:6: in function (for generator)'
[string "@SharedXML\OptionsFrameTemplates.lua"]:107: in function OptionsList_ClearSelection'
[string "@SharedXML\OptionsFrameTemplates.lua"]:147: in function OptionsListButton_OnClick'
[string ":OnClick"]:2: in function <[string ":OnClick"]:1>

Locals:
(temporary) = nil
(temporary) = nil
(*temporary) = "table expected, got nil"
`
1x SharedXML\OptionsFrameTemplates.lua:94: attempt to index local 'panel' (a nil value)
[string "@SharedXML\OptionsFrameTemplates.lua"]:94: in function OptionsList_DisplayPanel'
[string "@SharedXML\OptionsFrameTemplates.lua"]:150: in function OptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
panel = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'panel' (a nil value)`

**Comment by MysticalOS** [comment]
`1x C stack overflow
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@DBM-GUI\modules\MainFramePrototype.lua"]:182: in function `DisplayFrame'
[string "@DBM-GUI\DBM-GUI-27fafc0.lua"]:746: in function <DBM-GUI\DBM-GUI.lua:449>
[string "@DBM-GUI\DBM-GUI-27fafc0.lua"]:777: in function <DBM-GUI\DBM-GUI.lua:773>

Locals:
(*temporary) = DBM_GUI_Option_8399 {
 0 = <userdata>
 mytype = "area"
 OnBackdropLoaded = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:12
 isStats = true
 backdropBorderColor = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 SetupTextureCoordinates = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:16
 OnBackdropSizeChanged = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:13
 HasBackdropInfo = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:18
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
 GetEdgeSize = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:14
 NineSlice = <unnamed> {
 }
 backdropColorAlpha = 0
 ApplyBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:22
 SetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:34
 layoutType = "TooltipDefaultLayout"
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 GetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:19
 GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 SetupPieceVisuals = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = DBM_GUI_Option_8399 {
 0 = <userdata>
 mytype = "area"
 OnBackdropLoaded = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:12
 isStats = true
 backdropBorderColor = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 SetupTextureCoordinates = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:16
 OnBackdropSizeChanged = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:13
 HasBackdropInfo = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:18
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
 GetEdgeSize = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:14
 NineSlice = <unnamed> {
 }
 backdropColorAlpha = 0
 ApplyBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:22
 SetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:34
 layoutType = "TooltipDefaultLayout"
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 GetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:19
 GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 SetupPieceVisuals = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
}
 = <function> defined =[C]:-1
 = <function> defined @DBM-GUI\DBM-GUI.lua:719
`
